# Generated by Django 6.0.2 on 2026-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_booking_date_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
